return {
	"nvim-treesitter/nvim-treesitter",
	lazy = false,
	priority = 1000,
	build = ":TSUpdate",
	event = { "BufReadPost", "BufNewFile" },
	opts = {
		ensure_installed = {
			"c",
			"cpp",
			"python",
			"lua",
			"html",
			"css",
			"json",
			"yaml",
			"javascript",
			"typescript",
			"java",
			"prisma",
			"bash",
			"solidity",
			"svelte",
			"vim",
			"vimdoc",
			"query",
		},
		auto_install = true,
		indent = { enable = true },
		highlight = { enable = true, disable = { "html" } },
	},
	config = function(_, opts)
		require("nvim-treesitter.configs").setup(opts)
	end,
}
